#!/usr/bin/env python3
"""
Applies English translations to all 310 questions in questions.json.
Reads the JSON, fills in all empty 'en' fields, and writes back.
"""

import json
import os

TRANSLATIONS = {
    1: {
        "q": "In Germany, people are allowed to openly say things against the government because ...",
        "A": "religious freedom applies here.",
        "B": "people pay taxes.",
        "C": "people have the right to vote.",
        "D": "freedom of expression applies here.",
    },
    2: {
        "q": "In Germany, parents can decide until their child's 14th birthday whether the child participates in ... classes at school.",
        "A": "history",
        "B": "religious education",
        "C": "political studies",
        "D": "language",
    },
    3: {
        "q": "Germany is a constitutional state. What does that mean?",
        "A": "All residents and the state must abide by the laws.",
        "B": "The state does not have to abide by the laws.",
        "C": "Only Germans must obey the laws.",
        "D": "The courts make the laws.",
    },
    4: {
        "q": "Which right is one of the fundamental rights in Germany?",
        "A": "Gun ownership",
        "B": "Right of the fist (law of the jungle)",
        "C": "Freedom of expression",
        "D": "Vigilante justice",
    },
    5: {
        "q": "Elections in Germany are free. What does that mean?",
        "A": "One may accept money for voting for a particular candidate.",
        "B": "Only people who have never been in prison may vote.",
        "C": "The voter may not be influenced or forced to vote in a particular way during the election, and must not suffer any disadvantages because of their vote.",
        "D": "All eligible voters must vote.",
    },
    6: {
        "q": "What is the German constitution called?",
        "A": "Volksgesetz (People's Law)",
        "B": "Bundesgesetz (Federal Law)",
        "C": "Deutsches Gesetz (German Law)",
        "D": "Grundgesetz (Basic Law)",
    },
    7: {
        "q": "Which right belongs to the fundamental rights guaranteed by the German constitution? The right to ...",
        "A": "freedom of faith and conscience",
        "B": "entertainment",
        "C": "work",
        "D": "housing",
    },
    8: {
        "q": "What is not stated in the Basic Law of Germany?",
        "A": "Human dignity is inviolable.",
        "B": "Everyone should have the same amount of money.",
        "C": "Every person may express their opinion.",
        "D": "All are equal before the law.",
    },
    9: {
        "q": "Which fundamental right in Germany applies only to foreigners? The fundamental right to ...",
        "A": "protection of the family",
        "B": "human dignity",
        "C": "asylum",
        "D": "freedom of expression",
    },
    10: {
        "q": "What is compatible with the German Basic Law?",
        "A": "corporal punishment",
        "B": "torture",
        "C": "the death penalty",
        "D": "a monetary fine",
    },
    11: {
        "q": "What is the constitution of the Federal Republic of Germany called?",
        "A": "Grundgesetz (Basic Law)",
        "B": "Bundesverfassung (Federal Constitution)",
        "C": "Gesetzbuch (Code of Law)",
        "D": "Verfassungsvertrag (Constitutional Treaty)",
    },
    12: {
        "q": "A party in the Bundestag wants to abolish freedom of the press. Is that possible?",
        "A": "Yes, if more than half of the members of the Bundestag are in favour.",
        "B": "Yes, but two-thirds of the members of the Bundestag must be in favour.",
        "C": "No, because freedom of the press is a fundamental right. It cannot be abolished.",
        "D": "No, because only the Bundesrat can abolish freedom of the press.",
    },
    13: {
        "q": 'In parliament, the term "opposition" refers to ...',
        "A": "the governing parties.",
        "B": "the parliamentary group with the most members.",
        "C": "all parties that were able to pass the 5% threshold in the last election.",
        "D": "all members of parliament who do not belong to the governing party/parties.",
    },
    14: {
        "q": "Freedom of expression in Germany means that I ...",
        "A": "may make false claims of fact on flyers.",
        "B": "can express my opinion in letters to the editor.",
        "C": "may wear Nazi symbols.",
        "D": "may express my opinion as long as I do not contradict the government.",
    },
    15: {
        "q": "What does the German Basic Law prohibit?",
        "A": "Military service",
        "B": "Forced labour",
        "C": "Free choice of profession",
        "D": "Working abroad",
    },
    16: {
        "q": "When is freedom of expression restricted in Germany?",
        "A": "When false claims about individuals are publicly spread",
        "B": "When opinions are expressed about the federal government",
        "C": "When discussing religions",
        "D": "When criticizing the state",
    },
    17: {
        "q": "German laws prohibit ...",
        "A": "freedom of expression for residents.",
        "B": "petitions by citizens.",
        "C": "freedom of assembly for residents.",
        "D": "unequal treatment of citizens by the state.",
    },
    18: {
        "q": "Which fundamental right is guaranteed in Article 1 of the Basic Law of the Federal Republic of Germany?",
        "A": "the inviolability of human dignity",
        "B": "the right to life",
        "C": "religious freedom",
        "D": "freedom of expression",
    },
    19: {
        "q": 'What is understood by the right of "freedom of movement" in Germany?',
        "A": "One may choose one's own place of residence.",
        "B": "One can change one's profession.",
        "C": "One may choose a different religion.",
        "D": "One may move about in public wearing very little clothing.",
    },
    20: {
        "q": "A party in Germany pursues the goal of establishing a dictatorship. It is then ...",
        "A": "tolerant.",
        "B": "oriented toward the rule of law.",
        "C": "law-abiding.",
        "D": "unconstitutional.",
    },
    21: {
        "q": "Which is the coat of arms of the Federal Republic of Germany? (Image 21)",
        "A": "1",
        "B": "2",
        "C": "3",
        "D": "4",
    },
    22: {
        "q": "What form of government does Germany have?",
        "A": "Monarchy",
        "B": "Dictatorship",
        "C": "Republic",
        "D": "Principality",
    },
    23: {
        "q": "In Germany, most employed people are ...",
        "A": "employed in small family businesses.",
        "B": "working voluntarily for a federal state.",
        "C": "self-employed with their own company.",
        "D": "employed by a company or government agency.",
    },
    24: {
        "q": "How many federal states does the Federal Republic of Germany have?",
        "A": "14",
        "B": "15",
        "C": "16",
        "D": "17",
    },
    25: {
        "q": "Which is not a federal state of the Federal Republic of Germany?",
        "A": "Alsace-Lorraine",
        "B": "North Rhine-Westphalia",
        "C": "Mecklenburg-Western Pomerania",
        "D": "Saxony-Anhalt",
    },
    26: {
        "q": "Germany is ...",
        "A": "a communist republic.",
        "B": "a democratic and social federal state.",
        "C": "a capitalist and social monarchy.",
        "D": "a social and socialist federal state.",
    },
    27: {
        "q": "Germany is ...",
        "A": "a socialist state.",
        "B": "a federal state.",
        "C": "a dictatorship.",
        "D": "a monarchy.",
    },
    28: {
        "q": "Who elects the members of the Bundestag in Germany?",
        "A": "the military",
        "B": "the business sector",
        "C": "the eligible voters",
        "D": "the administration",
    },
    29: {
        "q": "Which animal is the heraldic animal of the Federal Republic of Germany?",
        "A": "Lion",
        "B": "Eagle",
        "C": "Bear",
        "D": "Horse",
    },
    30: {
        "q": "What is not a characteristic of our democracy?",
        "A": "regular elections",
        "B": "press censorship",
        "C": "freedom of expression",
        "D": "multiple parties",
    },
    31: {
        "q": "The cooperation of parties to form a government is called in Germany ...",
        "A": "Unity.",
        "B": "Coalition.",
        "C": "Ministry.",
        "D": "Parliamentary group.",
    },
    32: {
        "q": "What is not a state power in Germany?",
        "A": "Legislation",
        "B": "Government",
        "C": "The press",
        "D": "Jurisdiction",
    },
    33: {
        "q": "Which statement is correct? In Germany ...",
        "A": "the state and religious communities are separated from each other.",
        "B": "the religious communities form the state.",
        "C": "the state is dependent on the religious communities.",
        "D": "the state and religious communities form a unity.",
    },
    34: {
        "q": "What is Germany not?",
        "A": "a democracy",
        "B": "a constitutional state",
        "C": "a monarchy",
        "D": "a welfare state",
    },
    35: {
        "q": "How does the German state finance social insurance?",
        "A": "Church taxes",
        "B": "Social contributions",
        "C": "Donations",
        "D": "Association membership fees",
    },
    36: {
        "q": "Which measure creates social security in Germany?",
        "A": "health insurance",
        "B": "car insurance",
        "C": "building insurance",
        "D": "liability insurance",
    },
    37: {
        "q": "What are the heads of government of most federal states in Germany called?",
        "A": "First Minister",
        "B": "Prime Minister",
        "C": "Senator",
        "D": "Minister President",
    },
    38: {
        "q": "The Federal Republic of Germany is a democratic and social ...",
        "A": "confederation of states.",
        "B": "federal state.",
        "C": "confederation.",
        "D": "centralized state.",
    },
    39: {
        "q": "What does every German federal state have?",
        "A": "its own foreign minister",
        "B": "its own currency",
        "C": "its own army",
        "D": "its own government",
    },
    40: {
        "q": "With which words does the German national anthem begin?",
        "A": "Peoples, hear the signals ...",
        "B": "Unity and justice and freedom ...",
        "C": "Joy, beautiful spark of the gods ...",
        "D": "Germany, united fatherland ...",
    },
    41: {
        "q": "Why are there more than one party in a democracy?",
        "A": "because this way the different opinions of the citizens are represented",
        "B": "so that bribery in politics is limited",
        "C": "to prevent political demonstrations",
        "D": "to stimulate economic competition",
    },
    42: {
        "q": "Who passes a new law in Germany?",
        "A": "the government",
        "B": "the parliament",
        "C": "the courts",
        "D": "the police",
    },
    43: {
        "q": "When can a party be banned in Germany?",
        "A": "when its election campaign is too expensive",
        "B": "when it fights against the constitution",
        "C": "when it criticizes the head of state",
        "D": "when its program proposes a new direction",
    },
    44: {
        "q": "Whom can a citizen in Germany not elect directly?",
        "A": "Members of the EU Parliament",
        "B": "the Federal President",
        "C": "State parliament members",
        "D": "Bundestag members",
    },
    45: {
        "q": "To which type of insurance does long-term care insurance belong?",
        "A": "Social insurance",
        "B": "Accident insurance",
        "C": "Household contents insurance",
        "D": "Liability and fire insurance",
    },
    46: {
        "q": "The German state has many tasks. Which task is among them?",
        "A": "It builds roads and schools.",
        "B": "It sells food and clothing.",
        "C": "It provides all residents with free newspapers.",
        "D": "It produces cars and buses.",
    },
    47: {
        "q": "The German state has many tasks. Which task does not belong to them?",
        "A": "It pays for holiday trips for all citizens.",
        "B": "It pays child benefits.",
        "C": "It supports museums.",
        "D": "It promotes athletes.",
    },
    48: {
        "q": "Which body does not belong to the constitutional organs of Germany?",
        "A": "the Bundesrat",
        "B": "the Federal President",
        "C": "the citizens' assembly",
        "D": "the government",
    },
    49: {
        "q": "Who determines education policy in Germany?",
        "A": "the teachers",
        "B": "the federal states",
        "C": "the Ministry for Family Affairs",
        "D": "the universities",
    },
    50: {
        "q": "The economic system in Germany is called ...",
        "A": "free centralized economy.",
        "B": "social market economy.",
        "C": "controlled centralized economy.",
        "D": "planned economy.",
    },
    51: {
        "q": "It is not part of a democratic constitutional state that ...",
        "A": "people can express criticism of the government.",
        "B": "citizens may participate in peaceful demonstrations.",
        "C": "people are arrested without reason by a private police force.",
        "D": "someone commits a crime and is therefore arrested.",
    },
    52: {
        "q": '"Popular sovereignty" means: All state authority emanates from the ...',
        "A": "people.",
        "B": "Bundestag.",
        "C": "Prussian king.",
        "D": "Federal Constitutional Court.",
    },
    53: {
        "q": 'What does "constitutional state" mean in Germany?',
        "A": "The state is always right.",
        "B": "There are only right-wing parties.",
        "C": "The citizens decide on the laws.",
        "D": "The state must abide by the laws.",
    },
    54: {
        "q": "What is not a state power in Germany?",
        "A": "Legislative",
        "B": "Judiciary",
        "C": "Executive",
        "D": "Directive",
    },
    55: {
        "q": "What does this image show? (Image 55)",
        "A": "the seat of the Bundestag in Berlin",
        "B": "the Federal Constitutional Court in Karlsruhe",
        "C": "the Bundesrat building in Berlin",
        "D": "the Federal Chancellery in Berlin",
    },
    56: {
        "q": "Which office in Germany belongs to the municipal administration?",
        "A": "Parish office",
        "B": "Public order office",
        "C": "Tax office",
        "D": "Foreign Office",
    },
    57: {
        "q": "Who is usually elected President of the German Bundestag?",
        "A": "the oldest member of parliament",
        "B": "the Minister President of the largest federal state",
        "C": "a former Federal Chancellor",
        "D": "a member of the strongest parliamentary group",
    },
    58: {
        "q": "Who appoints the ministers of the federal government in Germany?",
        "A": "the President of the Federal Constitutional Court",
        "B": "the Federal President",
        "C": "the President of the Bundesrat",
        "D": "the President of the Bundestag",
    },
    59: {
        "q": 'Which parties merged in Germany in 2007 to form the party "Die Linke"?',
        "A": "CDU and SSW",
        "B": "PDS and WASG",
        "C": "CSU and FDP",
        "D": "Buendnis 90/Die Gruenen and SPD",
    },
    60: {
        "q": "In Germany, the Bundestag and the Bundesrat belong to the ...",
        "A": "Executive.",
        "B": "Legislative.",
        "C": "Directive.",
        "D": "Judiciary.",
    },
    61: {
        "q": 'What does "popular sovereignty" mean?',
        "A": "The king/queen rules over the people.",
        "B": "The Federal Constitutional Court stands above the constitution.",
        "C": "The interest groups exercise sovereignty together with the government.",
        "D": "All state authority emanates from the people.",
    },
    62: {
        "q": "When the parliament of a German federal state is elected, it is called a ...",
        "A": "municipal election.",
        "B": "state parliament election.",
        "C": "European election.",
        "D": "Bundestag election.",
    },
    63: {
        "q": "What does not belong to the executive in Germany?",
        "A": "the police",
        "B": "the courts",
        "C": "the tax office",
        "D": "the ministries",
    },
    64: {
        "q": "The Federal Republic of Germany today is divided into ...",
        "A": "four occupation zones.",
        "B": "an eastern state and a western state.",
        "C": "16 cantons.",
        "D": "the federation, the states, and the municipalities.",
    },
    65: {
        "q": "It is not among the tasks of the German Bundestag to ...",
        "A": "draft laws.",
        "B": "control the federal government.",
        "C": "elect the Federal Chancellor.",
        "D": "form the federal cabinet.",
    },
    66: {
        "q": "Who wrote the text of the German national anthem?",
        "A": "Friedrich von Schiller",
        "B": "Clemens Brentano",
        "C": "Johann Wolfgang von Goethe",
        "D": "Heinrich Hoffmann von Fallersleben",
    },
    67: {
        "q": "What is primarily a task of the federal states in Germany?",
        "A": "Defence policy",
        "B": "Foreign policy",
        "C": "Economic policy",
        "D": "Education policy",
    },
    68: {
        "q": "Why does the state control the school system in Germany?",
        "A": "because there are only state schools in Germany",
        "B": "because all students must have a school diploma",
        "C": "because there are different schools in the federal states",
        "D": "because it is its duty according to the Basic Law",
    },
    69: {
        "q": "The Federal Republic of Germany has a three-tier administrative structure. What is the lowest political level called?",
        "A": "City councils",
        "B": "District councils",
        "C": "Municipalities",
        "D": "District offices",
    },
    70: {
        "q": "German Federal President Gustav Heinemann presents Helmut Schmidt with the certificate of appointment as German Federal Chancellor in 1974. What is one of the duties of the German Federal President? (Image 70)",
        "A": "He/She conducts government business.",
        "B": "He/She controls the governing party.",
        "C": "He/She selects the ministers.",
        "D": "He/She proposes the Chancellor for election.",
    },
    71: {
        "q": "Where does the German Federal Chancellor spend most of their time? Most often he/she is ...",
        "A": "in Bonn, because the Federal Chancellery and the Bundestag are located there.",
        "B": "at Schloss Meseberg, the guest house of the federal government, to receive state guests.",
        "C": "at Schloss Bellevue, the official residence of the Federal President, to receive state guests.",
        "D": "in Berlin, because the Federal Chancellery and the Bundestag are located there.",
    },
    72: {
        "q": "What is the name of the current Federal Chancellor of Germany?",
        "A": "Gerhard Schroeder",
        "B": "Juergen Ruettgers",
        "C": "Klaus Wowereit",
        "D": "Angela Merkel",
    },
    73: {
        "q": "The two largest parliamentary groups in the German Bundestag are currently called ...",
        "A": "CDU/CSU and SPD.",
        "B": "Die Linke and Buendnis 90/Die Gruenen.",
        "C": "FDP and SPD.",
        "D": "Die Linke and FDP.",
    },
    74: {
        "q": "What is the parliament for all of Germany called?",
        "A": "Bundesversammlung (Federal Assembly)",
        "B": "Volkskammer (People's Chamber)",
        "C": "Bundestag",
        "D": "Bundesgerichtshof (Federal Court of Justice)",
    },
    75: {
        "q": "What is the name of Germany's current head of state?",
        "A": "Joachim Gauck",
        "B": "Norbert Lammert",
        "C": "Wolfgang Thierse",
        "D": "Edmund Stoiber",
    },
    76: {
        "q": "What does the abbreviation CDU stand for in Germany?",
        "A": "Christliche Deutsche Union",
        "B": "Club Deutscher Unternehmer",
        "C": "Christlicher Deutscher Umweltschutz",
        "D": "Christlich Demokratische Union",
    },
    77: {
        "q": "What is the Bundeswehr?",
        "A": "the German police",
        "B": "a German port",
        "C": "a German citizens' initiative",
        "D": "the German army",
    },
    78: {
        "q": "What does the abbreviation SPD stand for?",
        "A": "Sozialistische Partei Deutschlands",
        "B": "Sozialpolitische Partei Deutschlands",
        "C": "Sozialdemokratische Partei Deutschlands",
        "D": "Sozialgerechte Partei Deutschlands",
    },
    79: {
        "q": "What does the abbreviation FDP stand for in Germany?",
        "A": "Friedliche Demonstrative Partei",
        "B": "Freie Deutschland Partei",
        "C": "Fuehrende Demokratische Partei",
        "D": "Freie Demokratische Partei",
    },
    80: {
        "q": "Which court in Germany is responsible for interpreting the Basic Law?",
        "A": "Higher Regional Court",
        "B": "Local Court",
        "C": "Federal Constitutional Court",
        "D": "Administrative Court",
    },
    81: {
        "q": "Who elects the Federal Chancellor in Germany?",
        "A": "the Bundesrat",
        "B": "the Federal Assembly",
        "C": "the people",
        "D": "the Bundestag",
    },
    82: {
        "q": "Who leads the German Federal Cabinet?",
        "A": "the President of the Bundestag",
        "B": "the Federal President",
        "C": "the President of the Bundesrat",
        "D": "the Federal Chancellor",
    },
    83: {
        "q": "Who elects the German Federal Chancellor?",
        "A": "the people",
        "B": "the Federal Assembly",
        "C": "the Bundestag",
        "D": "the Federal Government",
    },
    84: {
        "q": "What is the main task of the German Federal President? He/She ...",
        "A": "governs the country.",
        "B": "drafts the laws.",
        "C": "represents the country.",
        "D": "monitors compliance with the laws.",
    },
    85: {
        "q": "Who makes up the German Bundesrat?",
        "A": "the members of the Bundestag",
        "B": "the ministers of the Federal Government",
        "C": "the government representatives of the federal states",
        "D": "the party members",
    },
    86: {
        "q": "Who elects the Federal President in Germany?",
        "A": "the Federal Assembly",
        "B": "the Bundesrat",
        "C": "the Federal Parliament",
        "D": "the Federal Constitutional Court",
    },
    87: {
        "q": "Who is the head of state of the Federal Republic of Germany?",
        "A": "the Federal Chancellor",
        "B": "the Federal President",
        "C": "the President of the Bundesrat",
        "D": "the President of the Bundestag",
    },
    88: {
        "q": "The parliamentary opposition in the German Bundestag ...",
        "A": "monitors the government.",
        "B": "decides who becomes Federal Minister.",
        "C": "determines who sits in the Bundesrat.",
        "D": "proposes the heads of government of the federal states.",
    },
    89: {
        "q": "What is the term used in Germany for the group of members of parliament belonging to one party?",
        "A": "Association",
        "B": "Council of Elders",
        "C": "Parliamentary group",
        "D": "Opposition",
    },
    90: {
        "q": "The German federal states participate in federal legislation through ...",
        "A": "the Bundesrat.",
        "B": "the Federal Assembly.",
        "C": "the Bundestag.",
        "D": "the Federal Government.",
    },
    91: {
        "q": "In Germany, a change of government in a federal state can have effects on federal politics. Governing becomes ...",
        "A": "more difficult if this changes the majority in the Bundestag.",
        "B": "easier if new parties enter the Bundesrat as a result.",
        "C": "more difficult if this changes the majority in the Bundesrat.",
        "D": "easier if the federal state in question is a wealthy one.",
    },
    92: {
        "q": "What does the abbreviation CSU stand for in Germany?",
        "A": "Christlich Sichere Union",
        "B": "Christlich Sueddeutsche Union",
        "C": "Christlich Sozialer Unternehmerverband",
        "D": "Christlich Soziale Union",
    },
    93: {
        "q": 'The more "second votes" a party receives in a Bundestag election, the ...',
        "A": "fewer first votes it can have.",
        "B": "more direct candidates of the party enter parliament.",
        "C": "greater the risk of having to form a coalition.",
        "D": "more seats the party receives in parliament.",
    },
    94: {
        "q": "From what age may one participate in the election to the German Bundestag?",
        "A": "16",
        "B": "18",
        "C": "21",
        "D": "23",
    },
    95: {
        "q": "What applies to most children in Germany?",
        "A": "Compulsory voting",
        "B": "Compulsory schooling",
        "C": "Duty of confidentiality",
        "D": "Compulsory religion",
    },
    96: {
        "q": "What must every German citizen possess from the age of 16?",
        "A": "a passport",
        "B": "an identity card",
        "C": "a social security card",
        "D": "a driver's license",
    },
    97: {
        "q": "What do you automatically pay in Germany when you are permanently employed?",
        "A": "Social insurance",
        "B": "Social welfare",
        "C": "Child benefit",
        "D": "Housing benefit",
    },
    98: {
        "q": "When members of the German Bundestag switch their parliamentary group, ...",
        "A": "they are no longer allowed to participate in parliamentary sessions.",
        "B": "the government can lose its majority.",
        "C": "the Federal President must give his/her consent beforehand.",
        "D": "the voters of these members may vote again.",
    },
    99: {
        "q": "Who pays for social insurance in Germany?",
        "A": "Employers and employees",
        "B": "Only employees",
        "C": "All citizens",
        "D": "Only employers",
    },
    100: {
        "q": "What does not belong to statutory social insurance?",
        "A": "Life insurance",
        "B": "Statutory pension insurance",
        "C": "Unemployment insurance",
        "D": "Long-term care insurance",
    },
    101: {
        "q": "Trade unions are interest groups of ...",
        "A": "young people.",
        "B": "employees.",
        "C": "retirees.",
        "D": "employers.",
    },
    102: {
        "q": "What honor can be bestowed in the Federal Republic of Germany for outstanding achievements? (Image 102)",
        "A": "Federal Cross of Merit",
        "B": "Federal Eagle",
        "C": "Patriotic Order of Merit",
        'D': 'Honorary title "Hero of the German Democratic Republic"',
    },
    103: {
        "q": 'What is referred to as a "traffic light coalition" in Germany?',
        "A": "the cooperation of CDU and CSU parliamentary groups in the Bundestag",
        "B": "the cooperation of SPD, FDP, and Buendnis 90/Die Gruenen in a government",
        "C": "the cooperation of CSU, Die Linke, and Buendnis 90/Die Gruenen in a government",
        "D": "the cooperation of CDU and SPD parliamentary groups in the Bundestag",
    },
    104: {
        "q": "A woman in Germany loses her job. What must not be the reason for this dismissal?",
        "A": "The woman has been sick for a long time and is unable to work.",
        "B": "The woman often came late to work.",
        "C": "The woman handles private matters during working hours.",
        "D": "The woman is having a baby and her boss knows it.",
    },
    105: {
        "q": "What is a task of election helpers in Germany?",
        "A": "They help elderly people cast their votes in the voting booth.",
        "B": "They write the election notifications before the election.",
        "C": "They pass on interim results to the media.",
        "D": "They count the votes after the end of the election.",
    },
    106: {
        "q": "In Germany, volunteer election helpers assist during elections. What is a task of election helpers?",
        "A": "They help children and elderly people with voting.",
        "B": "They write cards and letters indicating the polling station.",
        "C": "They pass on interim results to journalists.",
        "D": "They count the votes after the end of the election.",
    },
    107: {
        "q": "For how many years is the Bundestag elected in Germany?",
        "A": "2 years",
        "B": "4 years",
        "C": "6 years",
        "D": "8 years",
    },
    108: {
        "q": "In a Bundestag election in Germany, everyone may vote who ...",
        "A": "lives in the Federal Republic of Germany and wants to vote.",
        "B": "is a citizen of the Federal Republic of Germany and is at least 18 years old.",
        "C": "has lived in the Federal Republic of Germany for at least 3 years.",
        "D": "is a citizen of the Federal Republic of Germany and is at least 21 years old.",
    },
    109: {
        "q": "How often are there normally Bundestag elections in Germany?",
        "A": "every three years",
        "B": "every four years",
        "C": "every five years",
        "D": "every six years",
    },
    110: {
        "q": "For how many years is the Bundestag elected in Germany?",
        "A": "2 years",
        "B": "3 years",
        "C": "4 years",
        "D": "5 years",
    },
    111: {
        "q": "In Germany, one is allowed to vote. What does that mean?",
        "A": "All German citizens may vote once they have reached the minimum age.",
        "B": "Only married persons may vote.",
        "C": "Only persons with a permanent job may vote.",
        "D": "All residents in Germany must vote.",
    },
    112: {
        "q": "Elections in Germany are ...",
        "A": "special.",
        "B": "secret.",
        "C": "job-related.",
        "D": "gender-dependent.",
    },
    113: {
        "q": "Elections in Germany are won by the party that ...",
        "A": "receives the most votes.",
        "B": "most men have predominantly voted for.",
        "C": "has received the most votes among workers.",
        "D": "has received the most first votes for its chancellor candidate.",
    },
    114: {
        "q": "Participating in democratic elections in Germany is ...",
        "A": "a duty.",
        "B": "a right.",
        "C": "a compulsion.",
        "D": "a burden.",
    },
    115: {
        "q": 'What does "active suffrage" mean in Germany?',
        "A": "One can be elected.",
        "B": "One must go and vote.",
        "C": "One can vote.",
        "D": "One must go to the vote counting.",
    },
    116: {
        "q": "If you are allowed to vote in a Bundestag election in Germany, that is called ...",
        "A": "active election campaign.",
        "B": "active election procedure.",
        "C": "active electioneering.",
        "D": "active suffrage.",
    },
    117: {
        "q": "What minimum percentage of second votes must parties receive to be elected to the German Bundestag?",
        "A": "3%",
        "B": "4%",
        "C": "5%",
        "D": "6%",
    },
    118: {
        "q": "What does electoral law regulate in Germany?",
        "A": "Whoever is allowed to vote must vote.",
        "B": "Everyone who wants to can vote.",
        "C": "Whoever does not vote loses the right to vote.",
        "D": "Whoever is allowed to vote can vote.",
    },
    119: {
        "q": "Elections in Germany are free. What does that mean?",
        "A": "All convicted criminals are not allowed to vote.",
        "B": "If I want to go vote, my employer must give me time off.",
        "C": "Every person can decide without coercion whether they want to vote and whom they want to vote for.",
        "D": "I can freely decide where I want to go to vote.",
    },
    120: {
        "q": "The electoral system in Germany is a ...",
        "A": "census suffrage.",
        "B": "three-class suffrage.",
        "C": "majority and proportional representation system.",
        "D": "general male suffrage.",
    },
    121: {
        "q": "A party wants to enter the German Bundestag. But it must have a minimum share of votes. This is called ...",
        "A": "5% threshold.",
        "B": "Admission limit.",
        "C": "Base value.",
        "D": "Guideline.",
    },
    122: {
        "q": "What principle do elections in Germany follow? Elections in Germany are ...",
        "A": "free, equal, secret.",
        "B": "open, secure, free.",
        "C": "closed, equal, secure.",
        "D": "secure, open, voluntary.",
    },
    123: {
        "q": 'What is the "5% threshold" in Germany?',
        "A": "Voting rule in the Bundestag for small parties",
        "B": "Attendance check in the Bundestag for votes",
        "C": "Minimum share of voter votes to enter parliament",
        "D": "Attendance check in the Bundesrat for votes",
    },
    124: {
        "q": "The Bundestag election in Germany is the election of ...",
        "A": "the Federal Chancellor.",
        "B": "the state parliaments.",
        "C": "the parliament for Germany.",
        "D": "the Federal President.",
    },
    125: {
        "q": "In a democracy, one function of regular elections is ...",
        "A": "to force citizens to cast their vote.",
        "B": "to enable a change of government according to the will of the voter majority.",
        "C": "to maintain existing laws in the country.",
        "D": "to give the poor more power.",
    },
    126: {
        "q": "What do eligible voters in Germany receive before an election?",
        "A": "an election notification from the municipality",
        "B": "a voting permit from the Federal President",
        "C": "a notification from the Federal Assembly",
        "D": "a notification from the parish office",
    },
    127: {
        "q": "Why does the 5% threshold exist in the electoral law of the Federal Republic of Germany?",
        "A": "the programs of many small parties have many things in common.",
        "B": "citizens can lose their orientation with many small parties.",
        "C": "many small parties make forming a government more difficult.",
        "D": "the small parties do not have enough money to pay the politicians.",
    },
    128: {
        "q": "Members of parliament who are elected by the citizens are called ...",
        "A": "Representatives.",
        "B": "Chancellors.",
        "C": "Ambassadors.",
        "D": "Minister Presidents.",
    },
    129: {
        "q": "Elected by the people in Germany is ...",
        "A": "the Federal Chancellor.",
        "B": "the Minister President of a federal state.",
        "C": "the Bundestag.",
        "D": "the Federal President.",
    },
    130: {
        "q": "Which ballot would be valid in a Bundestag election? (Image 130)",
        "A": "1",
        "B": "2",
        "C": "3",
        "D": "4",
    },
    131: {
        "q": "In Germany, a mayor is ...",
        "A": "the head of a school.",
        "B": "the head of a bank.",
        "C": "the head of a municipality.",
        "D": "the chairperson of a party.",
    },
    132: {
        "q": "Many people in Germany do volunteer work in their free time. What does that mean?",
        "A": "They work as soldiers.",
        "B": "They work voluntarily and without pay in clubs and associations.",
        "C": "They work in the Federal Government.",
        "D": "They work in a hospital and earn money doing so.",
    },
    133: {
        "q": "What is permitted in Bundestag and state parliament elections in Germany?",
        "A": "The husband also votes on behalf of his wife.",
        "B": "One can cast one's vote by postal vote.",
        "C": "One can cast one's vote by telephone on election day.",
        "D": "Children from the age of 14 are allowed to vote.",
    },
    134: {
        "q": "They want to abolish the bus line you always take to work. What can you do to keep the bus line?",
        "A": "I participate in a citizens' initiative for the preservation of the bus line or start one myself.",
        "B": "I become a member of a sports club and practice cycling.",
        "C": "I contact the tax office because as a taxpayer I have a right to the bus line.",
        "D": "I write a letter to the forestry office of the municipality.",
    },
    135: {
        "q": "Who do trade unions represent in Germany?",
        "A": "large companies",
        "B": "small companies",
        "C": "self-employed people",
        "D": "employees",
    },
    136: {
        "q": "In Germany, you go to the labor court in case of ...",
        "A": "an incorrect utility bill.",
        "B": "unjustified dismissal by your boss.",
        "C": "problems with neighbors.",
        "D": "difficulties after a traffic accident.",
    },
    137: {
        "q": "Which court in Germany is responsible for conflicts in the workplace?",
        "A": "the Family Court",
        "B": "the Criminal Court",
        "C": "the Labor Court",
        "D": "the Local Court",
    },
    138: {
        "q": "What can I do in Germany if my employer has unjustly dismissed me?",
        "A": "continue working and be friendly to the boss",
        "B": "initiate a dunning procedure against the employer",
        "C": "file a wrongful dismissal claim",
        "D": "report the employer to the police",
    },
    139: {
        "q": "When does a court trial take place in Germany? When someone ...",
        "A": "converts to another religion.",
        "B": "has committed a crime and is charged.",
        "C": "holds a different opinion than the government.",
        "D": "has parked their car incorrectly and it is towed.",
    },
    140: {
        "q": "What does a lay judge do in Germany? He/She ...",
        "A": "decides together with judges on guilt and punishment.",
        "B": "gives citizens legal advice.",
        "C": "issues documents.",
        "D": "defends the accused.",
    },
    141: {
        "q": "Who advises people on legal matters and represents them in court in Germany?",
        "A": "a lawyer",
        "B": "a judge",
        "C": "a lay judge",
        "D": "a prosecutor",
    },
    142: {
        "q": "What is the main task of a judge in Germany? A judge ...",
        "A": "represents citizens before a court.",
        "B": "works at a court and delivers verdicts.",
        "C": "changes laws.",
        "D": "supervises juveniles before the court.",
    },
    143: {
        "q": "A judge in Germany belongs to the ...",
        "A": "judiciary.",
        "B": "executive.",
        "C": "operative.",
        "D": "legislature.",
    },
    144: {
        "q": "A judge in Germany belongs to the ...",
        "A": "executive power.",
        "B": "judicial power.",
        "C": "planning power.",
        "D": "legislative power.",
    },
    145: {
        "q": "In Germany, state power is divided. For which branch of state power does a judge work?",
        "A": "judiciary.",
        "B": "executive.",
        "C": "press.",
        "D": "legislature.",
    },
    146: {
        "q": "What do you call a proceeding before a court in Germany?",
        "A": "Program",
        "B": "Procedure",
        "C": "Protocol",
        "D": "Trial",
    },
    147: {
        "q": "What is the work of a judge in Germany?",
        "A": "Governing Germany",
        "B": "Administering justice",
        "C": "Making plans",
        "D": "Enacting laws",
    },
    148: {
        "q": "What is a task of the police in Germany?",
        "A": "to defend the country",
        "B": "to eavesdrop on citizens",
        "C": "to pass laws",
        "D": "to monitor compliance with laws",
    },
    149: {
        "q": "Who can become a lay judge in Germany?",
        "A": "all residents born in Germany over 18 years of age",
        "B": "all German citizens older than 24 and younger than 70 years",
        "C": "all persons who have lived in Germany for at least 5 years",
        "D": "only persons with a completed law degree",
    },
    150: {
        "q": "A lay judge in Germany is ...",
        "A": "the deputy of the city head.",
        "B": "a volunteer judge.",
        "C": "a member of a municipal council.",
        "D": "a person who has studied law.",
    },
    151: {
        "q": "Who built the Wall in Berlin?",
        "A": "Great Britain",
        "B": "the GDR",
        "C": "the Federal Republic of Germany",
        "D": "the USA",
    },
    152: {
        "q": "When were the National Socialists with Adolf Hitler in power in Germany?",
        "A": "1918 to 1923",
        "B": "1932 to 1950",
        "C": "1933 to 1945",
        "D": "1945 to 1989",
    },
    153: {
        "q": "What happened on 8 May 1945?",
        "A": "Death of Adolf Hitler",
        "B": "Beginning of the construction of the Berlin Wall",
        "C": "Election of Konrad Adenauer as Federal Chancellor",
        "D": "End of the Second World War in Europe",
    },
    154: {
        "q": "When did the Second World War end?",
        "A": "1933",
        "B": "1945",
        "C": "1949",
        "D": "1961",
    },
    155: {
        "q": "When were the National Socialists in power in Germany?",
        "A": "1888 to 1918",
        "B": "1921 to 1934",
        "C": "1933 to 1945",
        "D": "1949 to 1963",
    },
    156: {
        "q": "In which year did Hitler become Reichskanzler (Reich Chancellor)?",
        "A": "1923",
        "B": "1927",
        "C": "1933",
        "D": "1936",
    },
    157: {
        "q": "The National Socialists with Adolf Hitler established in 1933 in Germany ...",
        "A": "a dictatorship.",
        "B": "a democratic state.",
        "C": "a monarchy.",
        "D": "a principality.",
    },
    158: {
        "q": 'The "Third Reich" was a ...',
        "A": "dictatorship.",
        "B": "democracy.",
        "C": "monarchy.",
        "D": "council republic.",
    },
    159: {
        "q": "What did not exist in Germany during the time of National Socialism?",
        "A": "free elections",
        "B": "press censorship",
        "C": "arbitrary arrests",
        "D": "persecution of Jews",
    },
    160: {
        "q": "Which war lasted from 1939 to 1945?",
        "A": "the First World War",
        "B": "the Second World War",
        "C": "the Vietnam War",
        "D": "the Gulf War",
    },
    161: {
        "q": "What characterized the Nazi state? A policy of ...",
        "A": "state racism",
        "B": "freedom of expression",
        "C": "general freedom of religion",
        "D": "development of democracy",
    },
    162: {
        "q": "Claus Schenk Graf von Stauffenberg became famous for ...",
        "A": "a gold medal at the 1936 Olympic Games.",
        "B": "the construction of the Reichstag building.",
        "C": "the build-up of the Wehrmacht.",
        "D": "the assassination attempt on Hitler on 20 July 1944.",
    },
    163: {
        "q": "In which year did the National Socialists destroy synagogues and Jewish businesses in Germany?",
        "A": "1925",
        "B": "1930",
        "C": "1938",
        "D": "1945",
    },
    164: {
        "q": "What happened on 9 November 1938 in Germany?",
        "A": "With the attack on Poland, the Second World War begins.",
        "B": "The National Socialists lose an election and dissolve the Reichstag.",
        "C": "Jewish businesses and synagogues are destroyed by National Socialists and their supporters.",
        "D": "Hitler becomes Reich President and bans all parties.",
    },
    165: {
        "q": "What was the name of the first Federal Chancellor of the Federal Republic of Germany?",
        "A": "Konrad Adenauer",
        "B": "Kurt Georg Kiesinger",
        "C": "Helmut Schmidt",
        "D": "Willy Brandt",
    },
    166: {
        "q": 'At which demonstrations in Germany did the people chant "We are the people"?',
        "A": "at the workers' uprising in 1953 in the GDR",
        "B": "at the demonstrations in 1968 in the Federal Republic of Germany",
        "C": "at the anti-nuclear demonstrations in 1985 in the Federal Republic of Germany",
        "D": "at the Monday demonstrations in 1989 in the GDR",
    },
    167: {
        "q": 'Which countries were referred to as "Allied Occupation Powers" in Germany after the Second World War?',
        "A": "Soviet Union, Great Britain, Poland, Sweden",
        "B": "France, Soviet Union, Italy, Japan",
        "C": "USA, Soviet Union, Spain, Portugal",
        "D": "USA, Soviet Union, Great Britain, France",
    },
    168: {
        "q": 'Which country was not an "Allied Occupation Power" in Germany?',
        "A": "USA",
        "B": "Soviet Union",
        "C": "France",
        "D": "Japan",
    },
    169: {
        "q": "When was the Federal Republic of Germany founded?",
        "A": "1939",
        "B": "1945",
        "C": "1949",
        "D": "1951",
    },
    170: {
        "q": "What existed during the time of National Socialism in Germany?",
        "A": "the ban on political parties",
        "B": "the right to free development of one's personality",
        "C": "freedom of the press",
        "D": "the protection of human dignity",
    },
    171: {
        "q": "Social market economy means the economy ...",
        "A": "is governed solely by supply and demand.",
        "B": "is planned and controlled by the state; supply and demand are not taken into account.",
        "C": "is based on demand from abroad.",
        "D": "is based on supply and demand, but the state ensures social balance.",
    },
    172: {
        "q": "In which occupation zone was the GDR founded?",
        "A": "American occupation zone.",
        "B": "French occupation zone.",
        "C": "British occupation zone.",
        "D": "Soviet occupation zone.",
    },
    173: {
        "q": "The Federal Republic of Germany is a founding member of ...",
        "A": "the North Atlantic Treaty Organization (NATO).",
        "B": "the United Nations (UN).",
        "C": "the European Union (EU).",
        "D": "the Warsaw Pact.",
    },
    174: {
        "q": "When was the GDR founded?",
        "A": "1947",
        "B": "1949",
        "C": "1953",
        "D": "1956",
    },
    175: {
        "q": "How many occupation zones were there in Germany after the Second World War?",
        "A": "3",
        "B": "4",
        "C": "5",
        "D": "6",
    },
    176: {
        "q": "How were the occupation zones of Germany distributed after 1945? (Image 176)",
        "A": "1=Great Britain, 2=Soviet Union, 3=France, 4=USA",
        "B": "1=Soviet Union, 2=Great Britain, 3=USA, 4=France",
        "C": "1=Great Britain, 2=Soviet Union, 3=USA, 4=France",
        "D": "1=Great Britain, 2=USA, 3=Soviet Union, 4=France",
    },
    177: {
        "q": "Which German city was divided into four sectors after the Second World War?",
        "A": "Munich",
        "B": "Berlin",
        "C": "Dresden",
        "D": "Frankfurt/Oder",
    },
    178: {
        "q": "From June 1948 to May 1949, the citizens of West Berlin were supplied by an airlift. What circumstance was responsible for this?",
        "A": "For France, supplying the West Berlin population by airplane was more cost-effective.",
        "B": "The American soldiers were afraid of ambushes during land transport.",
        "C": "For Great Britain, supplying via the airlift was faster.",
        "D": "The Soviet Union cut off all land traffic.",
    },
    179: {
        "q": "How did the Second World War officially end in Europe?",
        "A": "with the death of Adolf Hitler",
        "B": "through Germany's unconditional surrender",
        "C": "with the withdrawal of Germans from the occupied territories",
        "D": "through a revolution in Germany",
    },
    180: {
        "q": "The first Federal Chancellor of the Federal Republic of Germany was ...",
        "A": "Ludwig Erhard.",
        "B": "Willy Brandt.",
        "C": "Konrad Adenauer.",
        "D": "Gerhard Schroeder.",
    },
    181: {
        "q": "What did Willy Brandt want to express with his kneeling in 1970 in the former Jewish ghetto in Warsaw? (Image 181)",
        "A": "He submitted to the former Allies.",
        "B": "He asked Poland and the Polish Jews for forgiveness.",
        "C": "He showed his humility before the Warsaw Pact.",
        "D": "He said a prayer at the Tomb of the Unknown Soldier.",
    },
    182: {
        "q": "Which parties were forcibly merged into the SED in 1946, the unity party of the later GDR?",
        "A": "KPD and SPD",
        "B": "SPD and CDU",
        "C": "CDU and FDP",
        "D": "KPD and CSU",
    },
    183: {
        "q": 'When did the "economic miracle" take place in the Federal Republic of Germany?',
        "A": "the 1940s",
        "B": "the 1950s",
        "C": "the 1970s",
        "D": "the 1980s",
    },
    184: {
        "q": 'What did the people in Germany call "Zero Hour" for a very long time?',
        "A": "This refers to the time after reunification in 1989.",
        "B": "This referred to the beginning of the Second World War.",
        "C": "This was understood as the end of the Second World War and the beginning of reconstruction.",
        "D": "This refers to the hour when the clock is changed from summer time to winter time.",
    },
    185: {
        "q": 'What did the expression "Iron Curtain" stand for? The isolation of ...',
        "A": "the Warsaw Pact against the West.",
        "B": "Northern Germany against Southern Germany.",
        "C": "Nazi Germany against the Allies.",
        "D": "Europe against the USA.",
    },
    186: {
        "q": "In 1953 there was an uprising in the GDR, which was commemorated for a long time as a public holiday in the Federal Republic of Germany. When was it?",
        "A": "1 May",
        "B": "17 June",
        "C": "20 July",
        "D": "9 November",
    },
    187: {
        "q": "Which German state had a black-red-gold flag with a hammer, compass, and wreath of grain? (Image 187)",
        "A": "Prussia",
        "B": "Federal Republic of Germany",
        "C": "Third Reich",
        "D": "GDR",
    },
    188: {
        "q": "In which year was the Wall in Berlin built?",
        "A": "1953",
        "B": "1956",
        "C": "1959",
        "D": "1961",
    },
    189: {
        "q": "When did the GDR build the Wall in Berlin?",
        "A": "1919",
        "B": "1933",
        "C": "1961",
        "D": "1990",
    },
    190: {
        "q": "What does the abbreviation DDR stand for?",
        "A": "Dritter Deutscher Rundfunk (Third German Broadcasting)",
        "B": "Die Deutsche Republik (The German Republic)",
        "C": "Dritte Deutsche Republik (Third German Republic)",
        "D": "Deutsche Demokratische Republik (German Democratic Republic)",
    },
    191: {
        "q": "When was the Wall in Berlin opened for everyone?",
        "A": "1987",
        "B": "1989",
        "C": "1992",
        "D": "1995",
    },
    192: {
        "q": "Which present-day German federal state formerly belonged to the territory of the GDR?",
        "A": "Brandenburg",
        "B": "Bayern (Bavaria)",
        "C": "Saarland",
        "D": "Hessen (Hesse)",
    },
    193: {
        "q": "From 1961 to 1989, Berlin was ...",
        "A": "without a mayor.",
        "B": "an independent state.",
        "C": "divided by a wall.",
        "D": "only reachable by airplane.",
    },
    194: {
        "q": "On 3 October, Germany celebrates the Day of German ...",
        "A": "Unity.",
        "B": "Nation.",
        "C": "Federal States.",
        "D": "Cities.",
    },
    195: {
        "q": "Which present-day German federal state formerly belonged to the territory of the GDR?",
        "A": "Hessen (Hesse)",
        "B": "Sachsen-Anhalt (Saxony-Anhalt)",
        "C": "Nordrhein-Westfalen (North Rhine-Westphalia)",
        "D": "Saarland",
    },
    196: {
        "q": 'Why is the time in autumn 1989 in the GDR called "Die Wende" (The Turning Point)?',
        "A": "from a dictatorship to a democracy.",
        "B": "from a liberal market economy to socialism.",
        "C": "from a monarchy to social democracy.",
        "D": "from a religious state to a communist state.",
    },
    197: {
        "q": "Which present-day German federal state formerly belonged to the territory of the GDR?",
        "A": "Thueringen (Thuringia)",
        "B": "Hessen (Hesse)",
        "C": "Bayern (Bavaria)",
        "D": "Bremen",
    },
    198: {
        "q": "Which present-day German federal state formerly belonged to the territory of the GDR?",
        "A": "Bayern (Bavaria)",
        "B": "Niedersachsen (Lower Saxony)",
        "C": "Sachsen (Saxony)",
        "D": "Baden-Wuerttemberg",
    },
    199: {
        "q": 'The abbreviation "Stasi" in the GDR referred to ...',
        "A": "the parliament.",
        "B": "the Ministry for State Security.",
        "C": "a ruling party.",
        "D": "the Ministry for Public Education.",
    },
    200: {
        "q": "Which present-day German federal state formerly belonged to the territory of the GDR?",
        "A": "Hessen (Hesse)",
        "B": "Schleswig-Holstein",
        "C": "Mecklenburg-Vorpommern (Mecklenburg-Western Pomerania)",
        "D": "Saarland",
    },
    201: {
        "q": "Which of the following lists contains only federal states that belonged to the territory of the former GDR?",
        "A": "Niedersachsen, Nordrhein-Westfalen, Hessen, Schleswig-Holstein, Brandenburg",
        "B": "Mecklenburg-Vorpommern, Brandenburg, Sachsen, Sachsen-Anhalt, Thueringen",
        "C": "Bayern, Baden-Wuerttemberg, Rheinland-Pfalz, Thueringen, Sachsen",
        "D": "Sachsen, Thueringen, Hessen, Niedersachsen, Brandenburg",
    },
    202: {
        "q": 'Who did the GDR belong to during the "Cold War"?',
        "A": "to the Western powers",
        "B": "to the Warsaw Pact",
        "C": "to NATO",
        "D": "to the non-aligned states",
    },
    203: {
        "q": "What was the economic system of the GDR called?",
        "A": "market economy",
        "B": "planned economy",
        "C": "supply and demand",
        "D": "capitalism",
    },
    204: {
        "q": "How did the Federal Republic of Germany and the GDR become one state?",
        "A": "The Federal Republic of Germany occupied the GDR.",
        "B": "Today's five eastern federal states joined the Federal Republic of Germany.",
        "C": "The western federal states joined the GDR.",
        "D": "The GDR occupied the Federal Republic of Germany.",
    },
    205: {
        "q": "With the accession of the GDR to the Federal Republic of Germany, the new federal states now also belong to ...",
        "A": "the European Union.",
        "B": "the Warsaw Pact.",
        "C": "OPEC.",
        "D": "the European Defence Community.",
    },
    206: {
        "q": 'What did the word "Monday demonstration" mean in Germany in 1989?',
        "A": "In the Federal Republic, demonstrations were only allowed on Mondays.",
        "B": "On Mondays there were demonstrations against the GDR regime.",
        "C": "On the first Monday of each month, demonstrators gathered in the Federal Republic of Germany.",
        "D": "On Mondays there were demonstrations in the GDR against the West.",
    },
    207: {
        "q": "In which military alliance was the GDR a member?",
        "A": "in NATO",
        "B": "in the Confederation of the Rhine",
        "C": "in the Warsaw Pact",
        "D": "in the European Alliance",
    },
    208: {
        "q": 'What was the "Stasi"?',
        "A": 'the secret service in the "Third Reich"',
        "B": "a famous German memorial",
        "C": "the secret service of the GDR",
        "D": "a German sports club during the Second World War",
    },
    209: {
        "q": "Which was the coat of arms of the German Democratic Republic? (Image 209)",
        "A": "1",
        "B": "2",
        "C": "3",
        "D": "4",
    },
    210: {
        "q": "What happened on 17 June 1953 in the GDR?",
        "A": "the ceremonial accession to the Warsaw Pact",
        "B": "nationwide strikes and a popular uprising",
        "C": "the 1st SED party congress",
        "D": "the first visit of Fidel Castro",
    },
    211: {
        "q": 'Which politician is associated with the "Eastern Treaties"?',
        "A": "Helmut Kohl",
        "B": "Willy Brandt",
        "C": "Mikhail Gorbachev",
        "D": "Ludwig Erhard",
    },
    212: {
        "q": "What is the full name of Germany?",
        "A": "Bundesstaat Deutschland",
        "B": "Bundeslaender Deutschland",
        "C": "Bundesrepublik Deutschland",
        "D": "Bundesbezirk Deutschland",
    },
    213: {
        "q": "How many inhabitants does Germany have?",
        "A": "70 million",
        "B": "78 million",
        "C": "80 million",
        "D": "90 million",
    },
    214: {
        "q": "What colours does the German flag have?",
        "A": "black-red-gold",
        "B": "red-white-black",
        "C": "black-red-green",
        "D": "black-yellow-red",
    },
    215: {
        "q": 'Who is referred to as the "Chancellor of German Unity"?',
        "A": "Gerhard Schroeder",
        "B": "Helmut Kohl",
        "C": "Konrad Adenauer",
        "D": "Helmut Schmidt",
    },
    216: {
        "q": "Which symbol can be seen in the plenary hall of the German Bundestag? (Image 216)",
        "A": "the Federal Eagle.",
        "B": "the flag of the city of Berlin.",
        "C": "the Imperial Eagle.",
        "D": "the Imperial Crown.",
    },
    217: {
        "q": "In which period did the German Democratic Republic exist?",
        "A": "1919 to 1927",
        "B": "1933 to 1945",
        "C": "1945 to 1961",
        "D": "1949 to 1990",
    },
    218: {
        "q": "How many federal states were added to the Federal Republic of Germany during reunification in 1990?",
        "A": "4",
        "B": "5",
        "C": "6",
        "D": "7",
    },
    219: {
        "q": "The Federal Republic of Germany has had its current borders since ...",
        "A": "1933.",
        "B": "1949.",
        "C": "1971.",
        "D": "1990.",
    },
    220: {
        "q": "27 January is an official day of remembrance in Germany. What does this day commemorate?",
        "A": "the end of the Second World War",
        "B": "the adoption of the Basic Law",
        "C": "the reunification of Germany",
        "D": "the victims of National Socialism",
    },
    221: {
        "q": "Germany is a member of the Schengen Agreement. What does that mean?",
        "A": "Germans can travel to many countries in Europe without passport control.",
        "B": "All people can enter Germany without identity checks.",
        "C": "Germans can travel to any country without passport control.",
        "D": "Germans can pay with the euro in any country.",
    },
    222: {
        "q": "Which country is a neighbouring country of Germany?",
        "A": "Hungary",
        "B": "Portugal",
        "C": "Spain",
        "D": "Switzerland",
    },
    223: {
        "q": "Which country is a neighbouring country of Germany?",
        "A": "Romania",
        "B": "Bulgaria",
        "C": "Poland",
        "D": "Greece",
    },
    224: {
        "q": "What does the abbreviation EU stand for?",
        "A": "Europaeische Unternehmen (European Enterprises)",
        "B": "Europaeische Union (European Union)",
        "C": "Einheitliche Union (Unified Union)",
        "D": "Euro Union",
    },
    225: {
        "q": "In which other country is there a large German-speaking population?",
        "A": "Czech Republic",
        "B": "Norway",
        "C": "Spain",
        "D": "Austria",
    },
    226: {
        "q": "Which is the flag of the European Union? (Image 226)",
        "A": "1",
        "B": "2",
        "C": "3",
        "D": "4",
    },
    227: {
        "q": "Which country is a neighboring country of Germany?",
        "A": "Finland",
        "B": "Denmark",
        "C": "Norway",
        "D": "Sweden",
    },
    228: {
        "q": "What is the accession of the GDR to the Federal Republic of Germany in 1990 generally called?",
        "A": "NATO eastward expansion",
        "B": "EU eastward expansion",
        "C": "German reunification",
        "D": "European Community",
    },
    229: {
        "q": "Which country is a neighboring country of Germany?",
        "A": "Spain",
        "B": "Bulgaria",
        "C": "Norway",
        "D": "Luxembourg",
    },
    230: {
        "q": "The European Parliament is elected regularly, namely every ...",
        "A": "5 years.",
        "B": "6 years.",
        "C": "7 years.",
        "D": "8 years.",
    },
    231: {
        "q": 'What does the term "European integration" mean?',
        "A": "It refers to American immigrants in Europe.",
        "B": "The term means the immigration stop to Europe.",
        "C": "It refers to European emigrants in the USA.",
        "D": "The term means the union of European states to form the EU.",
    },
    232: {
        "q": "Who is elected in the European election?",
        "A": "the European Commission",
        "B": "the countries that are allowed to join the EU",
        "C": "the members of the European Parliament",
        "D": "the European constitution",
    },
    233: {
        "q": "Which country is a neighboring country of Germany?",
        "A": "Czech Republic",
        "B": "Bulgaria",
        "C": "Greece",
        "D": "Portugal",
    },
    234: {
        "q": "Where is the seat of the European Parliament?",
        "A": "London",
        "B": "Paris",
        "C": "Berlin",
        "D": "Strasbourg",
    },
    235: {
        "q": "French President Francois Mitterrand and German Chancellor Helmut Kohl commemorate together in Verdun the dead of both World Wars. Which goal of the European Union becomes clear at this meeting? (Image 235)",
        "A": "Friendship between England and Germany",
        "B": "Freedom of travel to all EU countries",
        "C": "Peace and security in the EU countries",
        "D": "Uniform holidays in the EU countries",
    },
    236: {
        "q": "How many member states does the EU have today?",
        "A": "21",
        "B": "23",
        "C": "25",
        "D": "28",
    },
    237: {
        "q": 'In 2007, the 50th anniversary of the "Treaties of Rome" was celebrated. What was the content of the treaties?',
        "A": "Germany's accession to NATO",
        "B": "Founding of the European Economic Community (EEC)",
        "C": "Germany's obligation to pay reparations",
        "D": "Establishment of the Oder-Neisse line as the eastern border",
    },
    238: {
        "q": "In which locations does the European Parliament work?",
        "A": "Paris, London, and The Hague",
        "B": "Strasbourg, Luxembourg, and Brussels",
        "C": "Rome, Bern, and Vienna",
        "D": "Bonn, Zurich, and Milan",
    },
    239: {
        "q": "Through which treaties did the Federal Republic of Germany join together with other states to form the European Economic Community?",
        'A': 'through the "Hamburg Treaties"',
        'B': 'through the "Treaties of Rome"',
        'C': 'through the "Paris Treaties"',
        'D': 'through the "London Treaties"',
    },
    240: {
        "q": "Since when have people in Germany been paying with the euro in cash?",
        "A": "1995",
        "B": "1998",
        "C": "2002",
        "D": "2005",
    },
    241: {
        "q": "Mrs. Seger is having a child. What must she do to receive parental allowance?",
        "A": "She must write to her health insurance company.",
        "B": "She must submit an application to the parental allowance office.",
        "C": "She does not need to do anything, because she automatically receives parental allowance.",
        "D": "She must ask the employment office for permission.",
    },
    242: {
        "q": "Who decides whether a child in Germany goes to kindergarten?",
        "A": "the state",
        "B": "the federal states",
        "C": "the parents/legal guardians",
        "D": "the schools",
    },
    243: {
        "q": "Maik and Sybille want to hold a street demonstration with friends at their German place of residence. What must they do beforehand?",
        "A": "They must register the demonstration.",
        "B": "They do not need to do anything. In Germany, you may demonstrate anywhere at any time.",
        "C": "They cannot do anything, because demonstrations are fundamentally prohibited in Germany.",
        "D": "Maik and Sybille must found a new association, because only associations are allowed to demonstrate.",
    },
    244: {
        "q": "What school qualification do you normally need to begin studying at a university in Germany?",
        "A": "the Abitur",
        "B": "a diploma",
        "C": "a power of attorney (Prokura)",
        "D": "a journeyman's examination",
    },
    245: {
        "q": "Who is not allowed to live together as a couple in Germany?",
        "A": "Hans (20 years old) and Marie (19 years old)",
        "B": "Tom (20 years old) and Klaus (45 years old)",
        "C": "Sofie (35 years old) and Lisa (40 years old)",
        "D": "Anne (13 years old) and Tim (25 years old)",
    },
    246: {
        "q": "At what age is a person legally an adult in Germany?",
        "A": "16",
        "B": "18",
        "C": "19",
        "D": "21",
    },
    247: {
        "q": "A woman is pregnant. She is especially protected by law shortly before and after the birth of her child. What is this protection called?",
        "A": "Parental leave (Elternzeit)",
        "B": "Maternity protection (Mutterschutz)",
        "C": "Birth preparation (Geburtsvorbereitung)",
        "D": "Postpartum period (Wochenbett)",
    },
    248: {
        "q": "The upbringing of children in Germany is primarily the responsibility of ...",
        "A": "the state.",
        "B": "the parents.",
        "C": "the grandparents.",
        "D": "the schools.",
    },
    249: {
        "q": "Who is mainly responsible for raising children in Germany?",
        "A": "the state",
        "B": "the parents",
        "C": "the relatives",
        "D": "the schools",
    },
    250: {
        "q": "In Germany, you have the best chances of getting a well-paid job if you ...?",
        "A": "are Catholic.",
        "B": "are well educated.",
        "C": "are a woman.",
        "D": "are a member of a political party.",
    },
    251: {
        "q": "If you hit a child in Germany, ...",
        "A": "it is nobody's business.",
        "B": "it is only the family's business.",
        "C": "you cannot be punished for it.",
        "D": "you can be punished for it.",
    },
    252: {
        "q": "In Germany ...",
        "A": "you may only be married to one partner at the same time.",
        "B": "you can have multiple spouses at the same time.",
        "C": "you may not remarry if you were once married.",
        "D": "a woman may not remarry if her husband has died.",
    },
    253: {
        "q": "Where must you register if you move in Germany?",
        "A": "at the residents' registration office",
        "B": "at the civil registry office",
        "C": "at the public order office",
        "D": "at the trade office",
    },
    254: {
        "q": 'In Germany, married couples are allowed to get divorced. Usually, they must observe the "separation year." What does that mean?',
        "A": "The divorce process takes one year.",
        "B": "The man and woman are married for one year, then the divorce is possible.",
        "C": "The visitation rights for the children are valid for one year.",
        "D": "The man and woman lead separate lives for at least one year. After that, the divorce is possible.",
    },
    255: {
        "q": "For parenting problems, parents in Germany can receive help from the ...",
        "A": "public order office.",
        "B": "school authority.",
        "C": "youth welfare office.",
        "D": "health department.",
    },
    256: {
        "q": "A married couple wants to open a restaurant in Germany. What do they absolutely need for this?",
        "A": "a permit from the police",
        "B": "an approval from a political party",
        "C": "an approval from the residents' registration office",
        "D": "a restaurant license from the responsible authority",
    },
    257: {
        "q": "An adult woman wants to obtain her Abitur in Germany. She can do this at ...",
        "A": "a university.",
        "B": "an evening school (Abendgymnasium).",
        "C": "a secondary school (Hauptschule).",
        "D": "a private university.",
    },
    258: {
        "q": "What is the youth welfare office allowed to do in Germany?",
        "A": "It decides which school the child attends.",
        "B": "It can remove a child who is being beaten or forced to go hungry from the family.",
        "C": "It pays child benefit to the parents.",
        "D": "It checks whether the child attends kindergarten.",
    },
    259: {
        "q": "The Career Information Center (BIZ) at the Federal Employment Agency in Germany helps with ...",
        "A": "pension calculation.",
        "B": "searching for apprenticeships.",
        "C": "tax returns.",
        "D": "health insurance.",
    },
    260: {
        "q": "In Germany, a child in school has ...",
        "A": "the right to unlimited free time.",
        "B": "freedom to choose all subjects.",
        "C": "a claim to school fees.",
        "D": "a duty to attend.",
    },
    261: {
        "q": "A man wants to obtain his Abitur at the age of 30 in Germany. Where can he do this?",
        "A": "at a university",
        "B": "at an evening school (Abendgymnasium)",
        "C": "at a secondary school (Hauptschule)",
        "D": "at a private university",
    },
    262: {
        "q": "What does the principle of equal treatment mean in Germany?",
        "A": "No one may be disadvantaged, for example, because of a disability.",
        "B": "You may disadvantage other people if there are sufficient personal reasons for doing so.",
        "C": "No one may bring a claim against persons if they have been disadvantaged.",
        "D": "It is a law for everyone to donate money annually to disadvantaged groups.",
    },
    263: {
        "q": "In Germany, juveniles from the age of 14 are criminally responsible. This means: juveniles who are 14 years or older and violate criminal laws ...",
        "A": "are punished.",
        "B": "are treated like adults.",
        "C": "share the punishment with their parents.",
        "D": "are not punished.",
    },
    264: {
        "q": "At which festival do people in Germany wear colorful costumes and masks?",
        "A": "on Rose Monday (Rosenmontag)",
        "B": "on May Day",
        "C": "at Oktoberfest",
        "D": "at Pentecost (Pfingsten)",
    },
    265: {
        "q": "Where must you go first in Germany if you want to get married?",
        "A": "to the residents' registration office",
        "B": "to the public order office",
        "C": "to the employment agency",
        "D": "to the civil registry office (Standesamt)",
    },
    266: {
        "q": "When does the legal nighttime quiet period begin in Germany?",
        "A": "when the sun goes down",
        "B": "when the neighbors go to sleep",
        "C": "at 12 a.m., midnight",
        "D": "at 10 p.m.",
    },
    267: {
        "q": "A young woman in Germany, 22 years old, lives together with her boyfriend. The woman's parents do not approve because they do not like the boyfriend. What can the parents do?",
        "A": "They must respect the decision of their adult daughter.",
        "B": "They have the right to bring their daughter back to the parental home.",
        "C": "They can go to the police and report their daughter.",
        "D": "They look for another man for their daughter.",
    },
    268: {
        "q": "A young woman wants to get a driver's license. She is afraid of the exam because her native language is not German. What is correct?",
        "A": "She must live in Germany for at least ten years before she can get a driver's license.",
        "B": "If she does not speak German, she is not allowed to have a driver's license.",
        "C": "She must get her driver's license in the country where her language is spoken.",
        "D": "She may be able to take the theory exam in her native language. There are more than ten languages to choose from.",
    },
    269: {
        "q": "In Germany, children from the age of three until they start school have a right to ...",
        "A": "monthly pocket money.",
        "B": "a place in a sports club.",
        "C": "a kindergarten place.",
        "D": "a holiday pass.",
    },
    270: {
        "q": "The Volkshochschule (adult education center) in Germany is an institution ...",
        "A": "for religious instruction.",
        "B": "only for young people.",
        "C": "for continuing education.",
        "D": "only for retirees.",
    },
    271: {
        "q": "What is a Christmas tradition in Germany?",
        "A": "hiding colorful eggs",
        "B": "decorating a Christmas tree",
        "C": "dressing up in masks and costumes",
        "D": "placing pumpkins in front of the door",
    },
    272: {
        "q": "Which form of living is not permitted in Germany?",
        "A": "A man and a woman are divorced and live with new partners.",
        "B": "Two women live together.",
        "C": "A single father lives with his two children.",
        "D": "A man is married to two women at the same time.",
    },
    273: {
        "q": "For parenting problems in Germany, you go to the ...",
        "A": "doctor.",
        "B": "health department.",
        "C": "residents' registration office.",
        "D": "youth welfare office.",
    },
    274: {
        "q": "You intentionally opened a letter in Germany that was addressed to another person. What did you disregard?",
        "A": "the right to remain silent",
        "B": "the secrecy of correspondence",
        "C": "the duty of confidentiality",
        "D": "freedom of expression",
    },
    275: {
        "q": "What do you need in Germany for a divorce?",
        "A": "the consent of the parents",
        "B": "a doctor's certificate",
        "C": "the consent of the children",
        "D": "the assistance of a lawyer",
    },
    276: {
        "q": "What should you do if you are treated badly by your contact person at a German government office?",
        "A": "I cannot do anything.",
        "B": "I have to put up with this treatment.",
        "C": "I threaten the person.",
        "D": "I can file a complaint with the head of the authority.",
    },
    277: {
        "q": "A woman who has a two-year-old child applies for a job in Germany. What is an example of discrimination? She does not get the job only because she ...",
        "A": "does not speak English.",
        "B": "has salary expectations that are too high.",
        "C": "has no experience in this profession.",
        "D": "is a mother.",
    },
    278: {
        "q": "A man in a wheelchair applied for a position as an accountant. What is an example of discrimination? He does not get the job only because he ...",
        "A": "is in a wheelchair.",
        "B": "has no experience.",
        "C": "has salary expectations that are too high.",
        "D": "does not speak English.",
    },
    279: {
        "q": 'In most rental buildings in Germany, there is a "house rules" document. What is stated in such "house rules"? It lists ...',
        "A": "rules for using public transportation.",
        "B": "all tenants in the building.",
        "C": "rules that all residents must follow.",
        "D": "the address of the nearest public order office.",
    },
    280: {
        "q": "If you want to contest an incorrect tax assessment in Germany, you must ...",
        "A": "do nothing.",
        "B": "throw the assessment away.",
        "C": "file an objection.",
        "D": "wait until another assessment arrives.",
    },
    281: {
        "q": "Two friends want to go to a public swimming pool in Germany. Both have dark skin and are therefore not allowed in. Which right is being violated?",
        "A": "freedom of expression",
        "B": "equal treatment",
        "C": "freedom of assembly",
        "D": "freedom of movement",
    },
    282: {
        "q": "Which honorary office must German citizens take on when they are called upon to do so?",
        "A": "club trainer",
        "B": "election helper",
        "C": "library supervisor",
        "D": "teacher",
    },
    283: {
        "q": "What do you do if you receive an incorrect bill from a German government office?",
        "A": "I ignore the bill.",
        "B": "I file an objection with the authority.",
        "C": "I send the bill back to the authority.",
        "D": "I take the bill to the tax office.",
    },
    284: {
        "q": "What one needs to know for work is changing very rapidly in the future. What can one do?",
        "A": "It does not matter what you learn.",
        "B": "Adults must continue learning even after their training.",
        "C": "Children learn everything important for their career in school. After school, you do not need to continue learning.",
        "D": "Everyone must stop working earlier because everything is changing.",
    },
    285: {
        "q": "Mrs. Frost works as a permanent employee in an office. What does she not have to pay from her salary?",
        "A": "Income tax",
        "B": "Unemployment insurance contributions",
        "C": "Pension and health insurance contributions",
        "D": "Sales tax (Umsatzsteuer)",
    },
    286: {
        "q": "Which organization in a company helps employees with problems with the employer?",
        "A": "the works council (Betriebsrat)",
        "B": "the company auditor",
        "C": "the company group",
        "D": "the company management",
    },
    287: {
        "q": "You want to end your employment at a company in Germany. What must you observe?",
        "A": "the salary payments",
        "B": "the working hours",
        "C": "the notice period",
        "D": "the mandatory insurance",
    },
    288: {
        "q": "At which office must you generally register your dog in Germany?",
        "A": "at the tax office",
        "B": "at the residents' registration office",
        "C": "at the municipality (city or community)",
        "D": "at the health department",
    },
    289: {
        "q": "A man with dark skin applies for a position as a waiter at a restaurant in Germany. What is an example of discrimination? He does not get the job only because ...",
        "A": "his German language skills are too limited.",
        "B": "he has salary expectations that are too high.",
        "C": "he has dark skin.",
        "D": "he has no experience in the profession.",
    },
    290: {
        "q": "You bought a television in Germany. At home, you unpack the television, but it does not work. The television is broken. What can you do?",
        "A": "file a police report",
        "B": "make a complaint about the television (return/exchange it)",
        "C": "exchange the device without asking",
        "D": "extend the warranty",
    },
    291: {
        "q": "Why must you state on your tax return in Germany whether you belong to a church or not?",
        "A": "there is a church tax that is tied to income and wage tax.",
        "B": "it is important for statistics in Germany.",
        "C": "you have to pay more taxes if you do not belong to a church.",
        "D": "the church is responsible for the tax return.",
    },
    292: {
        "q": "People in Germany live according to the principle of religious tolerance. What does that mean?",
        "A": "No mosques may be built.",
        "B": "All people believe in God.",
        "C": "Everyone can believe what they want.",
        "D": "The state decides which God people believe in.",
    },
    293: {
        "q": "What is a tradition at Easter in Germany?",
        "A": "placing pumpkins in front of the door",
        "B": "decorating a Christmas tree",
        "C": "painting eggs",
        "D": "shooting rockets into the air",
    },
    294: {
        "q": "Pentecost (Pfingsten) is a ...",
        "A": "Christian holiday.",
        "B": "German memorial day.",
        "C": "international day of mourning.",
        "D": "Bavarian tradition.",
    },
    295: {
        "q": "Which religion has shaped European and German culture?",
        "A": "Hinduism",
        "B": "Christianity",
        "C": "Buddhism",
        "D": "Islam",
    },
    296: {
        "q": "In Germany, the last four weeks before Christmas are called ...",
        "A": "the Day of Repentance and Prayer (Buss- und Bettag).",
        "B": "the Harvest Festival (Erntedankfest).",
        "C": "Advent.",
        "D": "All Saints' Day (Allerheiligen).",
    },
    297: {
        "q": "From which country have the most migrants come to Germany?",
        "A": "Italy",
        "B": "Poland",
        "C": "Morocco",
        "D": "Turkey",
    },
    298: {
        "q": "In the GDR, migrants mainly came from ...",
        "A": "Vietnam, Poland, Mozambique.",
        "B": "France, Romania, Somalia.",
        "C": "Chile, Hungary, Zimbabwe.",
        "D": "North Korea, Mexico, Egypt.",
    },
    299: {
        "q": "Foreign workers who were recruited by the Federal Republic of Germany in the 1950s and 1960s were called ...",
        "A": "illegal workers (Schwarzarbeiter)",
        "B": "guest workers (Gastarbeiter)",
        "C": "temporary workers (Zeitarbeiter)",
        "D": "shift workers (Schichtarbeiter)",
    },
    300: {
        "q": "From which country did the first guest workers come to Germany?",
        "A": "Italy",
        "B": "Spain",
        "C": "Portugal",
        "D": "Turkey",
    },
}


def main():
    json_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "src", "data", "questions.json"
    )

    with open(json_path, "r", encoding="utf-8") as f:
        questions = json.load(f)

    updated = 0
    for q in questions:
        qid = q["id"]
        if qid in TRANSLATIONS:
            t = TRANSLATIONS[qid]
            q["question"]["en"] = t["q"]
            for opt in q["options"]:
                if opt["key"] in t:
                    opt["en"] = t[opt["key"]]
            updated += 1

    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(questions, f, ensure_ascii=False, indent=2)

    print(f"Updated {updated} questions with English translations.")
    # Verify no empty en fields in translated questions
    empty_count = 0
    for q in questions:
        if q["id"] <= 300:
            if not q["question"]["en"]:
                empty_count += 1
    print(f"Questions 1-300 with empty en: {empty_count}")


if __name__ == "__main__":
    main()
